version: '3.1'

services:

  redmine-postgres:
    container_name: redmine-postgres
    hostname: redmine-postgres
    image: postgres
    restart: always
    networks:
      - default
      - dbnetwork
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
  redmine:
    container_name: redmine
    hostname: redmine
    image: redmine
    restart: always
    networks:
      - default
      - dbnetwork
    depends_on:
      - redmine-postgres
    links:
      - redmine-postgres
    ports:
      - 8081:3000
    environment:
      REDMINE_DB_POSTGRES: redmine-postgres
      REDMINE_DB_PORT: 5432
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: 123456
      REDMINE_DB_DATABASE: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./redmine:/usr/src/redmine/files

networks:
  dbnetwork:
    external: true