version: "3"
services:
  nastools:
    image: syly948/nastools:2.9.1
    container_name: nastools
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/nastools/nastools/config:/config
      - /mnt/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
      - NASTOOL_AUTO_UPDATE=false
      - NASTOOL_CN_UPDATE=false
    # ports:
      # - 3000:3000
    
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - /etc/nastools/jellyfin/config:/config
      - /mnt/media/links:/data
    # ports:
      # - 8096:8096
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /etc/nastools/qbittorrent/config:/config
      - /mnt/media/downloads:/downloads
    # ports:
      # - 8080:8080
      # - 6881:6881
      # - 6881:6881/udp

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /etc/nastools/jackett/config:/config
      - /etc/nastools/jackett/downloads:/downloads
    # ports:
      # - 9117:9117

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: host
    restart: unless-stopped 
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Shanghai
    # ports:
      # - "${PORT:-8191}:8191"