version: '3.1'

services:

  gitlab-postgres:
    container_name: gitlab-postgres
    hostname: gitlab-postgres
    image: postgres
    restart: always
    networks:
      - default
      - dbnetwork
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
  gitlab-redis:
    container_name: gitlab-redis
    hostname: gitlab-redis
    image: redis
    restart: always
    networks:
      - default
      - dbnetwork
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
      - ./redis/config:/docker/config
    command: redis-server /docker/config/redis.conf
      
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    hostname: gitlab
    restart: always
    networks:
      - default
      - dbnetwork
    ports:
      - "2080:80"
      - "2022:22"
      - "2443:443"
    depends_on:
      - gitlab-postgres
      - gitlab-redis
    links:
      - gitlab-postgres
      - gitlab-redis
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.rqysir609.cc'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        #postgres
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'gitlab-postgres'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = '123456'
        gitlab_rails['db_database'] = "gitlab"
        #redis
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'gitlab-redis'
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = '891754'
        gitlab_rails['redis_database'] = '2'
        #nginx
        nginx['enable'] = false
        web_server['external_users'] = ['nginx']
        gitlab_rails['trusted_proxies'] = ['127.0.0.1', 'nginx']
        gitlab_rails['gitlab_ssh_host'] = 'gitlab.rqysir609.cc'
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8181"
        
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

networks:
  dbnetwork:
    external: true