version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 1080:80
      - 1443:443
    privileged: true
    networks:
      - default
      - dbnetwork
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d/:/etc/nginx/conf.d/
      - ./conf/ssl/:/etc/nginx/ssl/
      - ./html/:/usr/share/nginx/html/
      - ./logs/:/var/log/nginx/

networks:
  dbnetwork:
    external: true