version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./ssl/:/etc/nginx/ssl/
      - ./log/:/var/log/nginx/
      #- ./html:/usr/share/nginx/html
    deploy:
      mode: global
      restart_policy：  
        condition: on-failure