version: '3'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./ssl/:/etc/nginx/ssl/
      - ./logs/:/var/log/nginx/
      #- ./nginx/html:/usr/share/nginx/html

networks:
  nginx: