version: '3'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    restart: always
    # ports:
      # - 80:80
      # - 443:443
    networks:
      - host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/logs/:/var/log/nginx/
      #- ./nginx/html:/usr/share/nginx/html

# networks:
  # nginx: